### ISSUE TITLE
Incorrectly Formated ROS 1 `definitionStr` in README.md

### ISSUE THREAD

**Issue by shouhengyi** [foxglove/rosmsg#35]
**Description**
Instead of `geometry_msgs/msg/Pose`, I believe it should be `geometry_msgs/Pose`, i.e., removing the additional `msg/` in the middle.

```
const definitionStr = `# geometry_msgs/Pose
geometry_msgs/Point position
geometry_msgs/Quaternion orientation

===
MSG: geometry_msgs/Point
float64 x
float64 y
float64 z

===
MSG: geometry_msgs/Quaternion
float64 x
float64 y
float64 z
float64 w`;
```

Otherwise it will return:
```
webpack://@foxglove/rosmsg/./node_modules/nearley/lib/nearley.js:295
                var err = new Error(this.reportLexerError(e));
^
Error: invalid syntax at line 1 col 18:

  geometry_msgs/msg/Point position
                   ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

A "[" based on:
    arrayType →  ● "[" _ "]"
    main → _ customType ● arrayType __ field _ main$ebnf$6 complex
A "[" based on:
    arrayType →  ● "[" _ number _ "]"
    main → _ customType ● arrayType __ field _ main$ebnf$6 complex
A space token based on:
    _$subexpression$1 →  ● %space
    _ →  ● _$subexpression$1
    arrayType →  ● _
    main → _ customType ● arrayType __ field _ main$ebnf$6 complex
A space token based on:
    __ →  ● %space
    main → _ customType arrayType ● __ field _ main$ebnf$6 complex

    at Parser.feed (webpack://@foxglove/rosmsg/./node_modules/nearley/lib/nearley.js:295:1)
    at webpack://@foxglove/rosmsg/./src/parse.ts:114:12
    at Array.forEach (<anonymous>)
    at buildType (webpack://@foxglove/rosmsg/./src/parse.ts:106:9)
    at webpack://@foxglove/rosmsg/./src/parse.ts:68:13
    at Array.forEach (<anonymous>)
    at parse (webpack://@foxglove/rosmsg/./src/parse.ts:57:12)
    at Object.<anonymous> (/home/shouheng/Development/repos/experiments/rosmsg.ts:22:32)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1618:23) {
  offset: 1,
  token: undefined
}
```

- Version: 
- Platform:

**Steps To Reproduce**

**Expected Behavior**

**Comment by jtbandes** [comment]
Fixed in #36
